# CodeDeploy의 버전.
version: 0.0
os: linux
# 이동시킬 대상을 /(root)로 전부 다 하겠다는 말.
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

# CodeDeploy에서 EC2로 넘겨준 파일 모두 ec2-user 권한을 갖게 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user