# CodeDeploy의 버전.
version: 0.0
os: linux
# 이동시킬 대상을 /(root)로 전부 다 하겠다는 말.
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

# CodeDeploy에서 EC2로 넘겨준 파일 모두 ec2-user 권한을 갖게 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall: # 애플리케이션 구성할 때, 즉 ApplicationStart 전에 실행
    - location: stop.sh # nginx와 연결되어있지 않은 실행중이던 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart: # 중지된 서비스를 다시 시작할 때 사용
    - location: start.sh # 엔진엑스와 연결되어있지 않은 Port로 새 버전의 스프링부트로 시작
      timeout: 60
      runas: ec2-user
  ValidateService: # 배포가 성공적으로 완료됐는지 확인하는데 사용
    - location: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user